# HE CENTRAL CONTROL
# VERSIO 0.2
## TODO
# Cal fer la integració dels sensors de caudal


esphome:
  name: he-central-control
  friendly_name: HE Central Control

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MKvRRKoj2YtE/WieToKFo2jxp0ICOCdXSX1yNJqlgok="

ota:
  - platform: esphome
    password: "64be8379ae805d4498c13f1453f129ed"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "He-Central-Control"
    password: "aTdyXARdQz5u"

captive_portal:

#MAX31865 Control de temperatura aigua i fums 
spi:
  miso_pin: 22
  mosi_pin: 21
  clk_pin: 23

binary_sensor:
# PRESENCIA FOC
 - platform: template
   id: foc_ences
   name: "Foc encés"
   lambda: |-
      if (id(temp_fums).state > 45) {
        // Si la temperatura dels fums es superior a 45ºC considerem que hi ha foc
        return true;
      } else {
        // Si la temperatura dels fums es inferior a 45ºC considerem que no hi ha foc.
        return false;
      }
# ALARMA TEMP -> Hem d'obrir totes les vàlvules - Activar avis sonor
 - platform: template
   id: alarma_temp
   name: "Perill Sobretemperatura"
   lambda: |-
      if (id(temp_aigua).state > 85) {
        // Si la temperatura del aigua es superior a 85ºC considerem que hi ha perill sobretemperatura
        return true;
      } else {
        // Si la temperatura del aigua es inferior a 85ºC considerem que esta normal
        return false;
      }

# ALARMA PERILL TEMP
 - platform: template
   id: avis_alta_temp
   name: "Sobretemperatura"
   lambda: |-
      if (id(temp_aigua).state > 80) {
        // Si la temperatura del aigua es superior a 80ºC considerem que hi ha sobretemperatura
        return true;
      } else {
        // Si la temperatura del aigua es inferior a 80ºC considerem que esta normal
        return false;
      }      

# AVIS PRESSIO
 - platform: template
   id: avis_alta_pressio
   name: "Sobrepressió"
   lambda: |-
      if (id(pressio).state > 2.0) {
        // Si la pressio del aigua es superior a 2.0Bar considerem que hi ha sobrepressio
        return true;
      } else {
        // Si la pressio del aigua es inferior a 2.0Bar considerem que esta normal
        return false;
      } 

# ALARMA PERILL PRESSIO -> Per activar avís sonor
 - platform: template
   id: alarma_alta_pressio
   name: "Perill Sobrepressió"
   lambda: |-
      if (id(pressio).state > 2.5) {
        // Si la pressio del aigua es superior a 2.5Bar considerem que hi ha alarma sobrepressio
        return true;
      } else {
        // Si la pressio del aigua es inferior a 2.5Bar considerem que no hi ha alarma
        return false;
      }

# AVIS BAIXA PRESSIO
 - platform: template
   id: avis_baixa_pressio
   name: "Poca pressió"
   lambda: |-
      if (id(pressio).state < 1) {
        // Si la pressio del aigua es inferior a 1Bar considerem que hi ha poca pressió
        return true;
      } else {
        // Si la pressio del aigua es superior a 1Bar considerem que esta normal
        return false;
      }

# ALARMA BAIXA PRESSIO -> Per activar avís sonor
 - platform: template
   id: alarma_baixa_pressio
   name: "Perill poca pressió"
   lambda: |-
      if (id(pressio).state < 0.5) {
        // Si la pressio del aigua es inferior a 0.5Bar considerem que hi ha alarma baixa pressio
        return true;
      } else {
        // Si la pressio del aigua es superior a 0.5Bar considerem que no hi ha alarma baixa pressio
        return false;

# ACTIVACIO ALARMA SONORA - Si hi ha alarma baixa o alta pressió o sobretemperatura
 - platform: template
   id: alarma_sonora
   name: "Alarma"
   lambda: |-
      if ((alarma_baixa_pressio) or (alarma_alta_pressio) or (alarma_temp) or (alarma fallo sensors fum i temp caldera) {
        // Si tenim alguna alarma activada
        return true;
      } else {
        // Si no parem alarma
        return false;


sensor:
  # Temperatura de fums 
  - platform: max31865
    name: "Temp fums"
    id: temp_fums
    cs_pin: 19
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 30s
     # Optional variables:
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
   

  # Temperatura aigua caldera  
  - platform: max31865
    name: "Temp aigua"
    id: temp_aigua
    cs_pin: 20
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 30s
     # Optional variables:
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    on_value_range:
    # Aigua poc calenta per engegar bombes
     - below: 50 
       then:
        - switch.turn_off: rele_BP # Apaguem la bomba primaria
        - switch.turn_off: rele_BS # Apagauem la bomba secundaria
        - switch.turn_off: alarma_temp # Apaguem sonar alarma
    # Aigua calenta per engegar bomba primaria 
     - above: 50 
       below: 55
       then:
        - switch.turn_on: rele_BP # Engeguem la bomba primaria
        - switch.turn_off: rele_BS # Apaguem la bomba secundaria
        - switch.turn_off: alarma_temp # Apaguem sonar alarma
    # Aigua calenta en funcionament normal
     - above: 55 
       below: 80 
        - switch.turn_on: rele_BP # Engeguem la bomba primaria
        - switch.turn_on: rele_BS # Engeguem la bomba secundaria
        - switch.turn_off: alarma_temp # Apaguem sonar alarma
    # Aigua massa calenta reduim admissió aire    
     - above: 80
       below: 90
       then:
        - switch.turn_off: alarma_temp # Apaguem sonar alarma
    # Aigua massa calenta tanquem admissió aire i fem sonar alarma
     - above: 90.0
       then:
         - switch.turn_on: alarma_temp # Fem sonar alarma

# Sensor pressió 
# 0 - 0,5MPa  --> 0,5V - 4,5V (cal alimentar a 5V)
# Cal posar un divisor de tensió de 220ohms i 1K per ajustar la sortida al maxim 3,3V al llegir 4bar
  - platform: adc
    pin: GPIO35
    name: 'Pressió'
    id: pressio
    attenuation: 12db
    device_class: "pressure"
    state_class: "measurement" #Perque mantingui les dades
    accurancy_decimals: 2
    unit_of_measurement: "bar"
    filters:
      - calibrate_linear: 
        0,375 -> 0
        2,18 -> 3
        3,38 -> 5
      clamp:
        min_value: 0
    on_vaue_range:
      - below: 0.5 # Si la pressió es inferior a 0.5
        then:
          - switch.turn_on: alarma_pressio # Fem sonar alarma
      - above: 0.5 # Si la pressió esta dins limits seguretat 0.5-2.5
        below: 2.5
        then:
          - switch.turn_off: alarma_pressio # Parem alarma
      - above: 2.5 # Si la pressió passa de 2.5
        then:
          - switch.turn_on: alarma_pressio # Fem sonar alarma

    # Cal fer un sensor binari intern per saber si cal activar o no alarma, pq no engegui per pressió i tanqui per temp normal o al reves.

switch:
  - platform: gpio
    pin: GPIO18
    id: rele_BP # Rele bomba primaria

  - platform: gpio
    pin: GPIO19
    id: rele_BS # Rele bomba secundaria

  - platform: gpio
    pin: GPIO20
    id: alarma_sonora # Rele o alarma sonora per indicar emergencia

  
